# Generated by Django 2.1.2 on 2018-10-04 22:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='GUID')),
                ('tracked', models.BooleanField(default=False, verbose_name='Is Tracked')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Record Last Fetched')),
                ('id',
                 models.BigIntegerField(editable=False, primary_key=True, serialize=False, verbose_name='Event ID')),
            ],
        ),
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='GUID')),
                ('tracked', models.BooleanField(default=False, verbose_name='Is Tracked')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Date Record Last Fetched')),
                ('id',
                 models.BigIntegerField(editable=False, primary_key=True, serialize=False, verbose_name='Team ID')),
                ('name', models.CharField(max_length=8192, verbose_name='Team Name')),
                ('created', models.DateField(verbose_name='Created At')),
                ('fundraisingGoal', models.FloatField(null=True, verbose_name='Fundraising Goal')),
                ('numDonations', models.BigIntegerField(null=True, verbose_name='Donation Count')),
                ('sumDonations', models.FloatField(null=True, verbose_name='Donations Total')),
                ('event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                            to='ffdonations.EventModel', verbose_name='Event')),
            ],
        ),
    ]
