# Generated by Django 2.1.2 on 2018-10-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ffdonations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammodel',
            name='created',
            field=models.DateTimeField(verbose_name='Created At'),
        ),
    ]
