# Generated by Django 2.1.2 on 2018-10-04 23:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ffdonations', '0003_auto_20181004_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmodel',
            name='raw',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True, verbose_name='Raw Data'),
        ),
        migrations.AlterField(
            model_name='donormodel',
            name='raw',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True, verbose_name='Raw Data'),
        ),
        migrations.AlterField(
            model_name='participantmodel',
            name='raw',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True, verbose_name='Raw Data'),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='raw',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True, verbose_name='Raw Data'),
        ),
    ]
