# Generated by Django 2.1.2 on 2018-10-05 01:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('ffdonations', '0004_auto_20181004_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantmodel',
            name='avatarImage',
            field=models.URLField(null=True, verbose_name='Avatar Image'),
        ),
        migrations.AddField(
            model_name='participantmodel',
            name='campaignDate',
            field=models.DateTimeField(null=True, verbose_name='Campaign Date'),
        ),
        migrations.AddField(
            model_name='participantmodel',
            name='campaignName',
            field=models.CharField(max_length=8192, null=True, verbose_name='Campaign Name'),
        ),
        migrations.AddField(
            model_name='participantmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='participantmodel',
            name='displayName',
            field=models.CharField(default='FIXME', max_length=8192, verbose_name='Participant Name'),
        ),
        migrations.AddField(
            model_name='participantmodel',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='ffdonations.EventModel', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='participantmodel',
            name='fundraisingGoal',
            field=models.FloatField(null=True, verbose_name='Fundraising Goal'),
        ),
        migrations.AddField(
            model_name='participantmodel',
            name='isTeamCaptain',
            field=models.BooleanField(default=False, verbose_name='Is Team Captain'),
        ),
        migrations.AddField(
            model_name='participantmodel',
            name='numDonations',
            field=models.BigIntegerField(null=True, verbose_name='Donation Count'),
        ),
        migrations.AddField(
            model_name='participantmodel',
            name='sumDonations',
            field=models.FloatField(null=True, verbose_name='Donations Total'),
        ),
        migrations.AddField(
            model_name='participantmodel',
            name='team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='ffdonations.TeamModel', verbose_name='Team'),
        ),
    ]
