# Generated by Django 2.1.2 on 2018-10-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ffdonations', '0005_auto_20181004_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammodel',
            name='created',
            field=models.DateTimeField(null=True, verbose_name='Created At'),
        ),
    ]
