# Generated by Django 2.1.2 on 2018-10-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ffdonations', '0007_auto_20181004_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantmodel',
            name='sumPledges',
            field=models.FloatField(null=True, verbose_name='Pledges Total'),
        ),
    ]
