# Generated by Django 2.1.2 on 2018-10-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ffdonations', '0008_participantmodel_sumpledges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantmodel',
            name='isTeamCaptain',
            field=models.NullBooleanField(default=False, verbose_name='Is Team Captain'),
        ),
    ]
