# Generated by Django 2.1.2 on 2018-10-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ffdonations', '0009_auto_20181004_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donormodel',
            name='avatarImage',
            field=models.URLField(max_length=8192, null=True, verbose_name='Avatar Image'),
        ),
        migrations.AlterField(
            model_name='participantmodel',
            name='avatarImage',
            field=models.URLField(max_length=8192, null=True, verbose_name='Avatar Image'),
        ),
    ]
