# Generated by Django 2.1.2 on 2018-10-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ffdonations', '0010_auto_20181004_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationmodel',
            name='donor',
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='avatarImage',
            field=models.URLField(max_length=8192, null=True, verbose_name='Avatar Image'),
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='displayName',
            field=models.CharField(max_length=8192, null=True, verbose_name='Donor Name'),
        ),
        migrations.DeleteModel(
            name='DonorModel',
        ),
    ]
