# Generated by Django 2.1.2 on 2018-10-05 03:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ffdonations', '0011_auto_20181004_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationmodel',
            name='tracked',
        ),
    ]
