# Generated by Django 2.1.2 on 2018-10-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ffdonations', '0017_auto_20181005_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmodel',
            name='message',
            field=models.CharField(default='', max_length=1048576, verbose_name='Message'),
        ),
    ]
