# Generated by Django 2.1.2 on 2019-02-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ffdonations', '0019_auto_20181006_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='name',
            field=models.CharField(max_length=8192, null=True, verbose_name='Event Name'),
        ),
    ]
