# Generated by Django 2.2.4 on 2019-08-11 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('ffdonations', '0020_eventmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtiltifymodel',
            name='social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='ffdonations.SocailTiltifyModel', verbose_name='Social'),
        ),
    ]
