# Generated by Django 2.2.4 on 2019-08-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ffdonations', '0021_teamtiltifymodel_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtiltifymodel',
            name='about',
            field=models.CharField(max_length=8192, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='teamtiltifymodel',
            name='totalAmountRaised',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='Total Amount Raised'),
        ),
    ]
