# Generated by Django 2.2.7 on 2019-11-24 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ffdonations', '0022_auto_20190811_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationtiltifymodel',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='ffdonations.CampaignTiltifyModel', verbose_name='Campaign'),
        ),
    ]
