# Generated by Django 3.1.5 on 2021-01-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffdonations', '0023_donationtiltifymodel_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigntiltifymodel',
            name='supportable',
            field=models.BooleanField(null=True, verbose_name='Is Supportable'),
        ),
        migrations.AlterField(
            model_name='causetiltifymodel',
            name='mailchimpConnected',
            field=models.BooleanField(null=True, verbose_name='Mail Chimp Connected'),
        ),
        migrations.AlterField(
            model_name='causetiltifymodel',
            name='stripeConnected',
            field=models.BooleanField(null=True, verbose_name='Stripe Connected'),
        ),
        migrations.AlterField(
            model_name='participantmodel',
            name='isTeamCaptain',
            field=models.BooleanField(default=False, null=True, verbose_name='Is Team Captain'),
        ),
        migrations.AlterField(
            model_name='rewardtiltifymodel',
            name='active',
            field=models.BooleanField(null=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='rewardtiltifymodel',
            name='shippingAddressRequired',
            field=models.BooleanField(null=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='teamtiltifymodel',
            name='disbanded',
            field=models.BooleanField(null=True, verbose_name='Is Disbanded'),
        ),
        migrations.AlterField(
            model_name='teamtiltifymodel',
            name='inviteOnly',
            field=models.BooleanField(null=True, verbose_name='Is Invite Only Team'),
        ),
    ]
