# Generated by Django 3.1.5 on 2021-01-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffdonations', '0024_auto_20210114_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresstiltifymodel',
            name='raw',
            field=models.JSONField(default=dict, null=True, verbose_name='Raw Data'),
        ),
        migrations.AlterField(
            model_name='campaigntiltifymodel',
            name='raw',
            field=models.JSONField(default=dict, null=True, verbose_name='Raw Data'),
        ),
        migrations.AlterField(
            model_name='causetiltifymodel',
            name='raw',
            field=models.JSONField(default=dict, null=True, verbose_name='Raw Data'),
        ),
        migrations.AlterField(
            model_name='colortiltifymodel',
            name='raw',
            field=models.JSONField(default=dict, null=True, verbose_name='Raw Data'),
        ),
        migrations.AlterField(
            model_name='donationmodel',
            name='raw',
            field=models.JSONField(default=dict, null=True, verbose_name='Raw Data'),
        ),
        migrations.AlterField(
            model_name='donationtiltifymodel',
            name='raw',
            field=models.JSONField(default=dict, null=True, verbose_name='Raw Data'),
        ),
        migrations.AlterField(
            model_name='livestreamtiltifymodel',
            name='raw',
            field=models.JSONField(default=dict, null=True, verbose_name='Raw Data'),
        ),
        migrations.AlterField(
            model_name='mediatiltifymodel',
            name='raw',
            field=models.JSONField(default=dict, null=True, verbose_name='Raw Data'),
        ),
        migrations.AlterField(
            model_name='participantmodel',
            name='raw',
            field=models.JSONField(default=dict, null=True, verbose_name='Raw Data'),
        ),
        migrations.AlterField(
            model_name='rewardtiltifymodel',
            name='raw',
            field=models.JSONField(default=dict, null=True, verbose_name='Raw Data'),
        ),
        migrations.AlterField(
            model_name='settingstiltifymodel',
            name='raw',
            field=models.JSONField(default=dict, null=True, verbose_name='Raw Data'),
        ),
        migrations.AlterField(
            model_name='socailtiltifymodel',
            name='raw',
            field=models.JSONField(default=dict, null=True, verbose_name='Raw Data'),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='raw',
            field=models.JSONField(default=dict, null=True, verbose_name='Raw Data'),
        ),
        migrations.AlterField(
            model_name='teamtiltifymodel',
            name='raw',
            field=models.JSONField(default=dict, null=True, verbose_name='Raw Data'),
        ),
        migrations.AlterField(
            model_name='usertiltifymodel',
            name='raw',
            field=models.JSONField(default=dict, null=True, verbose_name='Raw Data'),
        ),
    ]
