"""Fixed table names for host and fw ifaces

Revision ID: b46249831ba4
Revises: e064e558b8f4
Create Date: 2017-11-22 09:52:03.412418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b46249831ba4'
down_revision = 'e064e558b8f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interfaces')
    op.drop_constraint(u'contacts_location_id_fkey', 'contacts', type_='foreignkey')
    op.create_foreign_key(None, 'contacts', 'locations', ['location_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(u'fw_interfaces_firewall_id_fkey', 'fw_interfaces', type_='foreignkey')
    op.drop_constraint(u'fw_interfaces_network_id_fkey', 'fw_interfaces', type_='foreignkey')
    op.create_foreign_key(None, 'fw_interfaces', 'firewalls', ['firewall_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'fw_interfaces', 'networks', ['network_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(u'host_interfaces_network_id_fkey', 'host_interfaces', type_='foreignkey')
    op.drop_constraint(u'host_interfaces_host_id_fkey', 'host_interfaces', type_='foreignkey')
    op.create_foreign_key(None, 'host_interfaces', 'hosts', ['host_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'host_interfaces', 'networks', ['network_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(u'locations_primary_contact_id_fkey', 'locations', type_='foreignkey')
    op.create_foreign_key(None, 'locations', 'contacts', ['primary_contact_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', schema='public', type_='foreignkey')
    op.create_foreign_key(u'locations_primary_contact_id_fkey', 'locations', 'contacts', ['primary_contact_id'], ['id'])
    op.drop_constraint(None, 'host_interfaces', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'host_interfaces', schema='public', type_='foreignkey')
    op.create_foreign_key(u'host_interfaces_host_id_fkey', 'host_interfaces', 'hosts', ['host_id'], ['id'])
    op.create_foreign_key(u'host_interfaces_network_id_fkey', 'host_interfaces', 'networks', ['network_id'], ['id'])
    op.drop_constraint(None, 'fw_interfaces', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'fw_interfaces', schema='public', type_='foreignkey')
    op.create_foreign_key(u'fw_interfaces_network_id_fkey', 'fw_interfaces', 'networks', ['network_id'], ['id'])
    op.create_foreign_key(u'fw_interfaces_firewall_id_fkey', 'fw_interfaces', 'firewalls', ['firewall_id'], ['id'])
    op.drop_constraint(None, 'contacts', schema='public', type_='foreignkey')
    op.create_foreign_key(u'contacts_location_id_fkey', 'contacts', 'locations', ['location_id'], ['id'])
    op.create_table('interfaces',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('guid', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('fqdn', sa.VARCHAR(length=4096), autoincrement=False, nullable=False),
    sa.Column('alt_fqdns', postgresql.ARRAY(sa.VARCHAR(length=4096)), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('netmask', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('mac_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('network_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mac_whitelisted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('firewall_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('host_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['firewall_id'], [u'firewalls.id'], name=u'interfaces_firewall_id_fkey'),
    sa.ForeignKeyConstraint(['host_id'], [u'hosts.id'], name=u'interfaces_host_id_fkey'),
    sa.ForeignKeyConstraint(['network_id'], [u'networks.id'], name=u'interfaces_network_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'interfaces_pkey')
    )
    # ### end Alembic commands ###
