"""init

Revision ID: da936addf8bf
Revises: 
Create Date: 2018-01-03 08:23:43.810861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da936addf8bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'contacts_location_id_fkey', 'contacts', type_='foreignkey')
    op.create_foreign_key(None, 'contacts', 'locations', ['location_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(u'fw_interfaces_firewall_id_fkey', 'fw_interfaces', type_='foreignkey')
    op.drop_constraint(u'fw_interfaces_network_id_fkey', 'fw_interfaces', type_='foreignkey')
    op.create_foreign_key(None, 'fw_interfaces', 'firewalls', ['firewall_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'fw_interfaces', 'networks', ['network_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(u'host_interfaces_network_id_fkey', 'host_interfaces', type_='foreignkey')
    op.drop_constraint(u'host_interfaces_host_id_fkey', 'host_interfaces', type_='foreignkey')
    op.create_foreign_key(None, 'host_interfaces', 'hosts', ['host_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'host_interfaces', 'networks', ['network_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(u'locations_primary_contact_id_fkey', 'locations', type_='foreignkey')
    op.create_foreign_key(None, 'locations', 'contacts', ['primary_contact_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', schema='public', type_='foreignkey')
    op.create_foreign_key(u'locations_primary_contact_id_fkey', 'locations', 'contacts', ['primary_contact_id'], ['id'])
    op.drop_constraint(None, 'host_interfaces', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'host_interfaces', schema='public', type_='foreignkey')
    op.create_foreign_key(u'host_interfaces_host_id_fkey', 'host_interfaces', 'hosts', ['host_id'], ['id'])
    op.create_foreign_key(u'host_interfaces_network_id_fkey', 'host_interfaces', 'networks', ['network_id'], ['id'])
    op.drop_constraint(None, 'fw_interfaces', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'fw_interfaces', schema='public', type_='foreignkey')
    op.create_foreign_key(u'fw_interfaces_network_id_fkey', 'fw_interfaces', 'networks', ['network_id'], ['id'])
    op.create_foreign_key(u'fw_interfaces_firewall_id_fkey', 'fw_interfaces', 'firewalls', ['firewall_id'], ['id'])
    op.drop_constraint(None, 'contacts', schema='public', type_='foreignkey')
    op.create_foreign_key(u'contacts_location_id_fkey', 'contacts', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###
