# Generated by Django 2.2.4 on 2019-08-11 22:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ffsfdc', '0002_elhistory_siteaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='ElHistoryC',
        ),
    ]
