# Generated by Django 2.2.10 on 2020-05-10 01:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=256, unique=True)),
                ('created', models.DateTimeField(null=True, verbose_name='Created At')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('is_live', models.BooleanField(default=False, verbose_name='Is Live')),
                ('active', models.BooleanField(default=True, verbose_name='Can be used for streaming')),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('is_live', models.BooleanField(default=False, verbose_name='Is Live')),
                ('started', models.DateTimeField(null=True, verbose_name='Started Streaming At')),
                ('ended', models.DateTimeField(null=True, verbose_name='Ended Streaming At')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ffstream.Key')),
            ],
        ),
    ]
