# Generated by Django 2.2.10 on 2020-05-10 01:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ffstream', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='owner',
        ),
    ]
