# Generated by Django 2.2.10 on 2020-05-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ffstream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='pull',
            field=models.BooleanField(blank=True, default=False, verbose_name='Can be used for pulling streaming'),
        ),
        migrations.AlterField(
            model_name='key',
            name='active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Can be used for streaming'),
        ),
        migrations.AlterField(
            model_name='key',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='key',
            name='id',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='key',
            name='is_live',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Live'),
        ),
    ]
