# Generated by Django 2.2.10 on 2020-09-16 18:30

from django.db import migrations, models


def set_saved_as(apps, schema_editor):
    Series = apps.get_model('ffstream', 'stream')
    for s in Series.objects.all().iterator():
        s.saved_as = "%s__%s" % (
            s.key.name,
            s.guid,
        )
        s.save()


def unset_saved_as(apps, schema_editor):
    Series = apps.get_model('ffstream', 'stream')
    for s in Series.objects.all().iterator():
        default_saved = "%s__%s" % (
            s.key.name,
            s.guid,
        )
        # Only revert default values
        if s.saved_as == default_saved:
            s.saved_as = None
            s.save()
        # else: Do nothing - has a custom value


class Migration(migrations.Migration):
    dependencies = [
        ('ffstream', '0002_auto_20200517_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='saved_as',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.RunPython(set_saved_as, unset_saved_as),
        migrations.AlterField(
            model_name='stream',
            name='saved_as',
            field=models.CharField(max_length=254, null=False),
        )
    ]
